#!/bin/bash
# Auto-generated by setup.sh
export ANTHROPIC_API_KEY="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"
/Library/Frameworks/Python.framework/Versions/3.14/bin/python3 "/Users/paamoah/Downloads/JARVIS 1.0/jarvis.py" briefing
