#!/bin/bash
# ============================================================
#  JARVIS Setup Script — macOS
#  Run once: bash setup.sh
# ============================================================

set -e

JARVIS_DIR="$(cd "$(dirname "$0")" && pwd)"
PYTHON=$(which python3)
PLIST_NAME="com.jarvis.briefing"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_NAME.plist"

echo ""
echo "╔══════════════════════════════════════╗"
echo "║         JARVIS Setup — macOS         ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ── 1. Install Python deps ──────────────────────────────────
echo "▶  Installing Python dependencies..."
pip3 install anthropic requests sounddevice openai-whisper --break-system-packages --quiet
echo "   ✓ Python deps installed"

# ── 2. Check for sox (optional, better audio recording) ─────
if ! command -v sox &>/dev/null; then
  echo ""
  echo "   ℹ️  sox not found. For better mic recording, install it:"
  echo "      brew install sox"
  echo "   (Jarvis will still work using sounddevice as fallback)"
else
  echo "   ✓ sox found"
fi

# ── 3. Prompt for Anthropic API key ─────────────────────────
echo ""
if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "▶  Anthropic API key not found in environment."
  read -p "   Paste your Anthropic API key: " API_KEY
  echo ""
  
  # Add to shell profile
  PROFILE=""
  if [ -f "$HOME/.zshrc" ]; then PROFILE="$HOME/.zshrc"
  elif [ -f "$HOME/.bash_profile" ]; then PROFILE="$HOME/.bash_profile"
  fi

  if [ -n "$PROFILE" ]; then
    echo "export ANTHROPIC_API_KEY=\"$API_KEY\"" >> "$PROFILE"
    echo "   ✓ API key saved to $PROFILE"
    export ANTHROPIC_API_KEY="$API_KEY"
  else
    echo "   ⚠️  Could not find shell profile. Add this manually:"
    echo "   export ANTHROPIC_API_KEY=\"$API_KEY\""
  fi
else
  echo "   ✓ Anthropic API key already set"
fi

# ── 4. Create shell launcher script ─────────────────────────
LAUNCHER="$JARVIS_DIR/run_briefing.sh"
cat > "$LAUNCHER" << EOF
#!/bin/bash
# Auto-generated by setup.sh
export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
$PYTHON "$JARVIS_DIR/jarvis.py" briefing
EOF
chmod +x "$LAUNCHER"
echo "   ✓ Launcher created: $LAUNCHER"

# ── 5. Register macOS LaunchAgent (boot trigger) ────────────
echo ""
echo "▶  Registering boot briefing LaunchAgent..."

cat > "$PLIST_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$PLIST_NAME</string>
  <key>ProgramArguments</key>
  <array>
    <string>$LAUNCHER</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>EnvironmentVariables</key>
  <dict>
    <key>ANTHROPIC_API_KEY</key>
    <string>$ANTHROPIC_API_KEY</string>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
  <key>StandardOutPath</key>
  <string>$JARVIS_DIR/logs/briefing.log</string>
  <key>StandardErrorPath</key>
  <string>$JARVIS_DIR/logs/briefing_err.log</string>
</dict>
</plist>
EOF

mkdir -p "$JARVIS_DIR/logs"
launchctl load "$PLIST_PATH" 2>/dev/null || true
echo "   ✓ LaunchAgent registered — briefing will run on every login"

# ── 6. Create jarvis alias ───────────────────────────────────
echo ""
PROFILE=""
if [ -f "$HOME/.zshrc" ]; then PROFILE="$HOME/.zshrc"
elif [ -f "$HOME/.bash_profile" ]; then PROFILE="$HOME/.bash_profile"; fi

if [ -n "$PROFILE" ]; then
  if ! grep -q "alias jarvis=" "$PROFILE" 2>/dev/null; then
    echo "alias jarvis='$PYTHON $JARVIS_DIR/jarvis.py chat'" >> "$PROFILE"
    echo "   ✓ Added 'jarvis' alias to $PROFILE"
    echo "   → Run 'source $PROFILE' or open a new terminal, then type: jarvis"
  else
    echo "   ✓ 'jarvis' alias already in profile"
  fi
fi

echo ""
echo "╔══════════════════════════════════════╗"
echo "║         ✅  Setup Complete           ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "  Boot briefing: fires automatically on every login"
echo "  Chat mode:     type 'jarvis' in any terminal"
echo "  Task manager:  open task_manager.html in your browser"
echo ""
echo "  First run: python3 jarvis.py briefing"
echo ""
